# ============================================================
# ESCC Neoadjuvant Project
# STEP 15B
# Freeze reviewed broad-cell-type labels for GSE197677
#
# Cluster 22:
#   Ambiguous_lowRNA
#
# IMPORTANT:
# - original object is NOT overwritten
# - no cells removed
# - no normalization
# - no reclustering
# - no malignant epithelial calling
# - no cross-dataset integration
# ============================================================

options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
  library(Seurat)
  library(data.table)
})

cat("\n============================================================\n")
cat("STEP 15B: FREEZE GSE197677 BROAD CELL TYPES\n")
cat("============================================================\n\n")

object_dir <- "03_objects/GSE197677"
table_dir  <- "06_tables/GSE197677/celltype"

dir.create(
  table_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

# ------------------------------------------------------------
# 1. Load reviewed candidate table
# ------------------------------------------------------------

candidate_file <- file.path(
  table_dir,
  "GSE197677_cluster_broad_celltype_candidates_FIXED.csv"
)

if (!file.exists(candidate_file)) {
  stop("Missing: ", candidate_file)
}

mapping <- fread(candidate_file)

mapping[
  ,
  cluster := as.character(cluster)
]

if (nrow(mapping) != 25) {
  stop(
    "Expected 25 occupied clusters, found ",
    nrow(mapping)
  )
}

if (uniqueN(mapping$cluster) != 25) {
  stop("Cluster mapping is not unique.")
}

# ------------------------------------------------------------
# 2. Freeze final broad labels
# ------------------------------------------------------------

mapping[
  ,
  broad_celltype_final :=
    as.character(
      suggested_broad_type
    )
]

# Manual review decision:
mapping[
  cluster == "22",
  broad_celltype_final :=
    "Ambiguous_lowRNA"
]

mapping[
  ,
  annotation_source :=
    fifelse(
      cluster == "22",
      "manual_review_15A4",
      "rawcount_marker_audit_15A2"
    )
]

mapping[
  ,
  annotation_note :=
    fifelse(
      cluster == "22",

      paste0(
        "Low RNA content; weak canonical epithelial/fibroblast markers; ",
        "fibroblast-reference similarity high but insufficient for ",
        "definitive lineage assignment"
      ),

      "Broad lineage accepted after raw-count marker audit"
    )
]

mapping[
  ,
  include_in_lineage_specific_primary :=
    cluster != "22"
]

cat("===== 1. FINAL CLUSTER MAPPING =====\n\n")

mapping[
  ,
  cluster_number :=
    as.integer(cluster)
]

setorder(
  mapping,
  cluster_number
)

mapping[
  ,
  cluster_number := NULL
]

print(
  mapping[
    ,
    .(
      cluster,
      n_cells,
      suggested_broad_type,
      broad_celltype_final,
      annotation_source,
      include_in_lineage_specific_primary
    )
  ],
  nrows = 100
)

# Save mapping before touching Seurat object
fwrite(
  mapping,
  file.path(
    table_dir,
    "GSE197677_FINAL_cluster_to_broad_celltype_mapping.csv"
  ),
  bom = TRUE
)

# ------------------------------------------------------------
# 3. Locate original integrated object
# ------------------------------------------------------------

rds_files <- list.files(
  object_dir,
  pattern = "\\.rds$",
  full.names = TRUE,
  ignore.case = TRUE
)

# Exclude any object generated by this step on rerun
rds_files <- rds_files[
  !grepl(
    "broadcelltype",
    basename(rds_files),
    ignore.case = TRUE
  )
]

hits <- rds_files[
  grepl(
    "integrated",
    basename(rds_files),
    ignore.case = TRUE
  )
]

if (length(hits) == 0) {
  stop("Original integrated GSE197677 RDS not found.")
}

object_file <- hits[1]

cat("\n===== 2. LOADING ORIGINAL OBJECT =====\n\n")
cat("File: ", object_file, "\n", sep = "")
cat("Large RDS — loading may take several minutes.\n\n")

obj <- readRDS(object_file)

cat("Extracting metadata from slot...\n")

md <- as.data.table(
  obj@meta.data,
  keep.rownames = "cell_id"
)

if (!"seurat_clusters" %in% colnames(md)) {
  stop("seurat_clusters missing.")
}

cluster_vector <- as.character(
  md$seurat_clusters
)

# ------------------------------------------------------------
# 4. Match cluster -> reviewed label
# ------------------------------------------------------------

idx <- match(
  cluster_vector,
  mapping$cluster
)

if (any(is.na(idx))) {

  bad <- unique(
    cluster_vector[
      is.na(idx)
    ]
  )

  stop(
    "Cells found in unmapped clusters: ",
    paste(bad, collapse = ", ")
  )
}

obj@meta.data$broad_celltype_final <-
  mapping$broad_celltype_final[
    idx
  ]

obj@meta.data$broad_celltype_annotation_source <-
  mapping$annotation_source[
    idx
  ]

obj@meta.data$include_in_lineage_specific_primary <-
  mapping$include_in_lineage_specific_primary[
    idx
  ]

# Explicitly preserve cluster 22 identity
obj@meta.data$cluster22_review_status <-
  ifelse(
    cluster_vector == "22",
    "Ambiguous_lowRNA",
    "Not_cluster22"
  )

# ------------------------------------------------------------
# 5. Validation
# ------------------------------------------------------------

cat("\n===== 3. CELL-LEVEL LABEL COUNTS =====\n\n")

label_counts <- as.data.table(
  table(
    obj@meta.data$broad_celltype_final
  )
)

setnames(
  label_counts,
  c(
    "broad_celltype",
    "n_cells"
  )
)

setorder(
  label_counts,
  -n_cells
)

print(label_counts)

cat(
  "\nTotal labelled cells: ",
  sum(label_counts$n_cells),
  "\n",
  sep = ""
)

cat(
  "Object cells        : ",
  nrow(md),
  "\n",
  sep = ""
)

if (
  sum(label_counts$n_cells) !=
  nrow(md)
) {
  stop("Not all cells received a broad label.")
}

# ------------------------------------------------------------
# 6. Cluster 22 validation
# ------------------------------------------------------------

cat("\n===== 4. CLUSTER 22 FINAL STATUS =====\n\n")

cluster22_n <- sum(
  cluster_vector == "22"
)

cluster22_labels <- unique(
  obj@meta.data$broad_celltype_final[
    cluster_vector == "22"
  ]
)

cat(
  "Cluster 22 cells : ",
  cluster22_n,
  "\n",
  sep = ""
)

cat(
  "Final label      : ",
  paste(
    cluster22_labels,
    collapse = ", "
  ),
  "\n",
  sep = ""
)

cat(
  "Primary lineage analysis included: ",
  unique(
    obj@meta.data$include_in_lineage_specific_primary[
      cluster_vector == "22"
    ]
  ),
  "\n",
  sep = ""
)

if (
  length(cluster22_labels) != 1 ||
  cluster22_labels != "Ambiguous_lowRNA"
) {
  stop("Cluster 22 override failed.")
}

# ------------------------------------------------------------
# 7. Sample x broad-cell-type counts
# ------------------------------------------------------------

group_fields <- intersect(
  c(
    "sample",
    "CellType",
    "NAC",
    "subtype",
    "broad_celltype_final"
  ),
  names(md)
)

sample_celltype <- md[
  ,
  .N,
  by = group_fields
]

setnames(
  sample_celltype,
  "N",
  "n_cells"
)

fwrite(
  sample_celltype,
  file.path(
    table_dir,
    "GSE197677_sample_by_final_broad_celltype_counts.csv"
  ),
  bom = TRUE
)

fwrite(
  label_counts,
  file.path(
    table_dir,
    "GSE197677_final_broad_celltype_counts.csv"
  ),
  bom = TRUE
)

# ------------------------------------------------------------
# 8. Save annotated COPY
# ------------------------------------------------------------

output_file <- file.path(
  object_dir,
  "GSE197677_integrated_broadcelltype_annotated.rds"
)

cat("\n===== 5. SAVING ANNOTATED COPY =====\n\n")

saveRDS(
  obj,
  output_file,
  compress = FALSE
)

size_gb <- file.info(
  output_file
)$size / 1024^3

cat(
  "Saved: ",
  output_file,
  "\n",
  sep = ""
)

cat(
  sprintf(
    "Size: %.2f GB\n",
    size_gb
  )
)

# ------------------------------------------------------------
# FINAL
# ------------------------------------------------------------

cat("\n============================================================\n")
cat("STEP 15B FINISHED ✓\n")
cat("GSE197677 BROAD CELL TYPES FROZEN ✓\n")
cat("============================================================\n\n")

cat(
  "Cluster 22 = Ambiguous_lowRNA ✓\n"
)

cat(
  "Cluster 22 retained in object ✓\n"
)

cat(
  "Cluster 22 excluded from lineage-specific primary analysis ✓\n"
)

cat("\nNo cells removed ✓\n")
cat("No normalization ✓\n")
cat("No reclustering ✓\n")
cat("No malignant epithelial calls ✓\n")
cat("No cross-dataset integration ✓\n")

cat("\nAnnotated object:\n")
cat(
  output_file,
  "\n"
)

cat("\nSTOP HERE.\n")
